### ISSUE TITLE
BUG - stuck at 2nd guess

### ISSUE THREAD

**Issue by kgarlow** [bubloo7/WordleSolver#1]
BUG
Solver got stuck on the word for January 12th.

narrowed down to: 12478 words
guess: aeros
What was the result?
a-rO-
narrowed down to: 23 words
guess: major
What was the result?
-A-OR
narrowed down to: 15 words
guess: major

**Comment by bubloo7** [comment]
Sorry for getting to this issue so late, I just saw this! 

I just cloned the repository and tried running it on my end and got the correct output: 
```
narrowed down to: 12478 words
guess: aeros
What was the result?
a_rO_
narrowed down to: 18 words
guess: major
What was the result?
_A_OR
narrowed down to: 10 words
guess: labor
What was the result?
_A_OR
narrowed down to: 7 words
guess: favor
What was the result?
FAVOR
answer is favor
```
I believe you ran the program before I pushed my "quick fix commit". If you run `git pull` or clone the repo again, it should work but please let me know if the problem persists!
